version: 2.1

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master

jobs:
  deploy:
    docker:
      - image: alpine/helm:2.13.0
      - entrypoint: [""]
    steps:
      - checkout
      # - run: echo "A more familiar hi"
      # - run: apk update && apk add curl && apk add --no-cache bash git openssh
      # - run: export NEW_REF=$CI_COMMIT_SHA
      # - run: if [ $CI_MERGE_REQUEST_TARGET_BRANCH_NAME ]; then export BASE_REF="origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"; else export BASE_REF="$CI_COMMIT_BEFORE_SHA";  fi
      # - run: echo $BASE_REF
      # - run: echo $NEW_REF
      # - run: git fetch origin
      # - run: git diff --name-only $NEW_REF $BASE_REF
      # - run: export COMPONENT="NOTSET"
      # - run: export CHANGED_FILES=$(git diff --name-only $NEW_REF $BASE_REF | sed 's|\([^\/]*\).*|\1|'  | uniq)
      # - run: for CHANGE in $CHANGED_FILES; do if [ "$COMPONENT" == "NOTSET" ]; then export COMPONENT="$CHANGE"; else echo "Only one component per PR should be changed" && exit 1;  fi; done
      # - run: if [ "$COMPONENT" == "NOTSET" ]; then echo "No component is changed!" && exit 1;  fi
      # - run: echo "Initializing Component => $COMPONENT"
      # - run: export COMPONENT_DIR="$COMPONENT"
      # - run: echo $COMPONENT_DIR 