version: 2.1

orbs:
  docker: circleci/docker@0.5.1

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master

jobs:
  deploy:
    docker:
      - image: alpine/helm:2.13.0
    steps:
      - checkout
      - run:
          name: Before Steps
          command: |
            # apk update && apk add curl && apk add --no-cache bash git openssh
            export NEW_REF=$CI_COMMIT_SHA
            if [ $CI_MERGE_REQUEST_TARGET_BRANCH_NAME ]; then export BASE_REF="origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"; else export BASE_REF="$CI_COMMIT_BEFORE_SHA";  fi
            echo $BASE_REF
            echo $NEW_REF
            git fetch origin
            git diff --name-only $NEW_REF $BASE_REF
            export COMPONENT="NOTSET"
            export CHANGED_FILES=$(git diff --name-only $NEW_REF $BASE_REF | sed 's|\([^\/]*\).*|\1|'  | uniq)
            for CHANGE in $CHANGED_FILES; do if [ "$COMPONENT" == "NOTSET" ]; then export COMPONENT="$CHANGE"; else echo "Only one component per PR should be changed" && exit 1;  fi; done
            if [ "$COMPONENT" == "NOTSET" ]; then echo "No component is changed!" && exit 1;  fi
            echo "Initializing Component => $COMPONENT"
            export COMPONENT_DIR="$COMPONENT"
            echo $COMPONENT_DIR
    