version: 2.1

orbs:
  docker: circleci/docker@0.5.1
  helm: circleci/helm@0.1.3
  multirepo: dnephin/multirepo@0.0.7

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: variables
          filters:
            branches:
              only:
                - master
                - test
      - upload:
          context: variables
          requires:
            - deploy
          filters:
            branches:
              only:
                - master
                - test

jobs:
  deploy:
    docker:
      - image: alpine/helm:2.13.0
    steps:
      - deploy:
          paths: "."
          run_on_upstream: false
      - run: echo $COMPONENT_DIR
      - run: echo $HELM_DIR
  
  
  upload:
    docker:
      - image: alpine/helm:2.13.0
    steps:
      - run: ls -la
      - run: echo $HELM_DIR
      - upload:
          paths: ""
    

commands:
  deploy:
    parameters:
      paths:
        type: string
        description: |
          A list of file paths used with 'git diff' to check for modification.
        default: ""
      upstream_branch:
        type: string
        description: |
          The upstream branch used with 'git merge-base' to find the most recent
          commit shared by HEAD and the upstream branch.
        default: origin/master
      working_directory:
        type: string
        description: |
          Directory to change to before executing the command.
        default: "$PWD"
      run_on_upstream:
        type: boolean
        description: |
          When run_on_upstream is true, and HEAD matches the upstream_branch the
          job always run. When false the job will not run when HEAD matches
          the upstream_branch.
        default: true
    steps:
      - checkout
      - run:
          name: Check if job should run
          command: |
            apk update && apk add curl && apk add --no-cache bash git openssh
            cd << parameters.working_directory >>
            export PAGER=$(git diff-tree --no-commit-id --name-only -r HEAD)
            echo "Changed Components are  => $PAGER"
            export COMPONENT="NOTSET"
            for CHANGE in $PAGER; do ENV_DIR=${CHANGE%%/*}; done
            for CHANGE in $PAGER; do if [ "$CHANGE" != ".*"   ] && [ "$ENV_DIR" == "${CHANGE%%/*}" ]; then export COMPONENT="$CHANGE"; else echo "Only one component per PR should be changed" && exit 1;  fi; done
            if [ "$COMPONENT" == "NOTSET" ]; then echo "No component is changed!" && exit 1;  fi
            echo "Initializing Component => $COMPONENT"
            echo $COMPONENT | cut -f1 -d"/"
            export COMPONENT_DIR="$COMPONENT%%/*"
            echo "Changed Dir => $COMPONENT_DIR"
            cd $COMPONENT_DIR
            helm init --client-only
            helm repo add charts https://charts.tmt.tools --username $TMT_CHARTS_USERNAME --password $TMT_CHARTS_PASSWORD
            helm dep build
            helm package .
            FILENAME="$(find . \( -name "$COMPONENT*.tgz" \) -exec basename {} \;)"
            if [ "$FILENAME" == "" ]; then echo "No Chart Version Found!" && exit 1;  fi
            echo $FILENAME
            curl --user $TMT_CHARTS_USERNAME:$TMT_CHARTS_PASSWORD --data-binary "@$FILENAME" https://charts.tmt.tools/api/charts

            


  upload:
    parameters:
      paths:
        type: string
        description: |
          A list of file paths used with 'git diff' to check for modification.
        default: "dome-backend"
    steps:
      - checkout
      - run:
          name: Upload Helm Chart
          command: |
            echo "Initializing Dir => $COMPONENT_DIR"
            cd $COMPONENT_DIR
            helm init --client-only
            helm repo add charts https://charts.tmt.tools --username $TMT_CHARTS_USERNAME --password $TMT_CHARTS_PASSWORD
            helm dep build
            helm package .
            FILENAME="$(find . \( -name "$COMPONENT*.tgz" \) -exec basename {} \;)"
            if [ "$FILENAME" == "" ]; then echo "No Chart Version Found!" && exit 1;  fi
            echo $FILENAME
            curl --user $TMT_CHARTS_USERNAME:$TMT_CHARTS_PASSWORD --data-binary "@$FILENAME" https://charts.tmt.tools/api/charts
